version: '3'

services:
  dataparsing:
    image: uwpath_dataparsing
    container_name: uwpath_dataparsing
    build: .
    environment:
      - ORACLE_DSN=db:1521/ORCLCDB
      - DB_USER=SYSTEM
      - DB_PASS=password
      - DB_HOST=uwpath_oracle_db
      - DB_PORT=1521
    networks:
      - uwpath_db_network

networks:
  uwpath_db_network:
    external: true
