name: int_deploy
on:
  push:
    branches:
      - int
      - pipeline-setup
      
jobs:
  cleanup:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - name: Cleaning up the $GITHUB_WORKSPACE as root from a Docker image
        # Volume auto mounted by gh actions pointing to the current working-directory
        run: find /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/. -name . -o -prune -exec rm -rf -- {} + || true

  deploy:
    name: deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      shell: bash
      env:
        DOCKER_USERNAME: ${{ secrets.UWPATH_DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.UWPATH_DOCKER_PASSWORD }}
      run: docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
    - name: Build Image
      run: |
          docker compose build
          docker image ls
    - name: Push to Registry
      run: |
          docker tag $(docker images uwpath_frontend --format "{{.ID}}") uwpathdocker/uwpath_frontend:int
          docker push uwpathdocker/uwpath_frontend:int
    - name: Clean Env
      if: always()
      run: |
        docker system prune --volumes -af
        docker logout
